In [72]:
import numpy as np

In [73]:
my_list = [1,2,3,4, 'xxx']

a = np.array(my_list)

In [74]:
a

array(['1', '2', '3', '4', 'xxx'], dtype='<U11')

In [75]:
b = np.array(my_list)

In [76]:
id(a), id(b)

(408160057264, 408152922832)

In [77]:
b = a

In [78]:
id(a), id(b)

(408160057264, 408160057264)

In [79]:
a = np.array(my_list)

id(a), id(b)

(408160057744, 408160057264)

In [87]:
a = np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [89]:
a = np.array(123)

In [90]:
a

array(123)

In [91]:
a = np.array('xxx')

In [92]:
a

array('xxx', dtype='<U3')

In [94]:
my_list = [1]

np.array(my_list)

array([1])

In [95]:
my_list = [1,2,3,4]

np.array(my_list, 'float')

array([1., 2., 3., 4.])

In [103]:
my_list = [1,2,3,4]

a = np.array(my_list, 'float')

In [104]:
a[:3]

array([1., 2., 3.])

In [105]:
a[1:3]

array([2., 3.])

In [116]:
my_list = [1,2,3,4, 'xxx']

a = np.asarray(my_list)
b = np.asarray(my_list)

id(a), id(b)

(408160612400, 408085139440)

In [127]:
my_list = [1,2,3,4, 'xxx']

a = np.asarray(my_list)
b = np.asarray(my_list)

my_list[0] = 'aaa'

a, b

(array(['1', '2', '3', '4', 'xxx'], dtype='<U11'),
 array(['1', '2', '3', '4', 'xxx'], dtype='<U11'))

In [128]:
my_list = [1,2,3,4, 'xxx']

a = np.array(my_list)
b = np.array(my_list)

my_list[0] = 'aaa'

a, b

(array(['1', '2', '3', '4', 'xxx'], dtype='<U11'),
 array(['1', '2', '3', '4', 'xxx'], dtype='<U11'))

In [129]:
my_list = [1,2,3,4, 'xxx']

a = np.array(my_list)
b = np.array(a)

a[0] = 'aaa'

a, b

(array(['aaa', '2', '3', '4', 'xxx'], dtype='<U11'),
 array(['1', '2', '3', '4', 'xxx'], dtype='<U11'))

In [130]:
my_list = [1,2,3,4, 'xxx']

a = np.asarray(my_list)
b = np.asarray(a)

a[0] = 'aaa'

a, b

(array(['aaa', '2', '3', '4', 'xxx'], dtype='<U11'),
 array(['aaa', '2', '3', '4', 'xxx'], dtype='<U11'))

In [131]:
my_list = [1,2,3,4, 'xxx']

a = np.asarray(my_list)
b = a

a[0] = 'aaa'

a, b

(array(['aaa', '2', '3', '4', 'xxx'], dtype='<U11'),
 array(['aaa', '2', '3', '4', 'xxx'], dtype='<U11'))

In [132]:
a.shape

(5,)