In [1]:
import numpy as np

In [2]:
array_5x5 = np.arange(1, 26)

In [3]:
array_5x5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [5]:
array_5x5.shape = (5, 5)

In [6]:
array_5x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
array_5x5.reshape(1, 25)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [8]:
array_5x5.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [9]:
array_5x5.sum()

325

In [17]:
np.array_split(array_5x5, 5, axis = 0)[0]

array([[1, 2, 3, 4, 5]])

In [18]:
array_5x5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
array_5x5[:, 0]

array([ 1,  6, 11, 16, 21])

In [21]:
array_5x5[0:2, :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [22]:
array_5x5[2]

array([11, 12, 13, 14, 15])

In [23]:
array_5x5[2, 0]

11

In [26]:
array_5x5 > 10

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [27]:
array_5x5[array_5x5 > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])